// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CreateSite(arg1) {
  return window['go']['main']['App']['CreateSite'](arg1);
}

export function CreateSiteAccount(arg1) {
  return window['go']['main']['App']['CreateSiteAccount'](arg1);
}

export function CreateTag(arg1) {
  return window['go']['main']['App']['CreateTag'](arg1);
}

export function DeleteSite(arg1) {
  return window['go']['main']['App']['DeleteSite'](arg1);
}

export function DeleteSiteAccount(arg1) {
  return window['go']['main']['App']['DeleteSiteAccount'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DownloadAndInstallUpdate() {
  return window['go']['main']['App']['DownloadAndInstallUpdate']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetSecondaryPasswordStatus() {
  return window['go']['main']['App']['GetSecondaryPasswordStatus']();
}

export function ListLogs() {
  return window['go']['main']['App']['ListLogs']();
}

export function ListSiteAccounts(arg1) {
  return window['go']['main']['App']['ListSiteAccounts'](arg1);
}

export function ListSites(arg1) {
  return window['go']['main']['App']['ListSites'](arg1);
}

export function ListTags() {
  return window['go']['main']['App']['ListTags']();
}

export function OpenSiteURL(arg1) {
  return window['go']['main']['App']['OpenSiteURL'](arg1);
}

export function RevealSiteAccountPassword(arg1, arg2) {
  return window['go']['main']['App']['RevealSiteAccountPassword'](arg1, arg2);
}

export function SetSecondaryPassword(arg1) {
  return window['go']['main']['App']['SetSecondaryPassword'](arg1);
}

export function SetSiteArchived(arg1, arg2) {
  return window['go']['main']['App']['SetSiteArchived'](arg1, arg2);
}

export function UpdateSite(arg1, arg2) {
  return window['go']['main']['App']['UpdateSite'](arg1, arg2);
}

export function UpdateSiteAccount(arg1, arg2) {
  return window['go']['main']['App']['UpdateSiteAccount'](arg1, arg2);
}
