// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateSite(arg1:model.CreateSiteInput):Promise<void>;

export function CreateSiteAccount(arg1:model.CreateSiteAccountInput):Promise<model.SiteAccountView>;

export function CreateTag(arg1:string):Promise<void>;

export function DeleteSite(arg1:number):Promise<void>;

export function DeleteSiteAccount(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function GetSecondaryPasswordStatus():Promise<model.SecondaryPasswordStatus>;

export function ListLogs():Promise<Array<model.AppLog>>;

export function ListSiteAccounts(arg1:number):Promise<Array<model.SiteAccountView>>;

export function ListSites(arg1:model.SiteFilter):Promise<Array<model.SiteView>>;

export function ListTags():Promise<Array<model.Tag>>;

export function OpenSiteURL(arg1:string):Promise<void>;

export function RevealSiteAccountPassword(arg1:number,arg2:string):Promise<string>;

export function SetSecondaryPassword(arg1:model.SetSecondaryPasswordInput):Promise<void>;

export function SetSiteArchived(arg1:number,arg2:boolean):Promise<void>;

export function UpdateSite(arg1:number,arg2:model.UpdateSiteInput):Promise<void>;

export function UpdateSiteAccount(arg1:number,arg2:model.UpdateSiteAccountInput):Promise<model.SiteAccountView>;
